#!/usr/bin/env bash
# This script uses scp to transfer file from one host to another
if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

if [ $# -ge 4 ];
then
    scp -o StrickHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrickHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
