#!/usr/bin/env bash
# This script uses scp to transfer file from one host to another
if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
if [ -n "$4" ];
then
    PATH_TO_SSH_KEY=$4;
fi;

if [ $# -ge 4 ];
then
    scp -o StrickHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
else
    scp -o StrickHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi;
