#!/usr/bin/env bash
# This script installs and configures the nginx server on a host

apt-get update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
ufw allow 'Nginx HTTP'
service nginx start
