#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header# a custom header

# install needed files
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 138836-web-01 52.86.83.227:80 check\n\tserver 138836-web-02 100.24.237.214:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
