#!/usr/bin/env bash
# This script creates the backup for a db

if [ "$1" ] ; then
    touch .mylogin.cnf
    printf "[client]\nuser = %s\npassword = %s" "root" "$1" >> .mylogin.cnf
    chmod 600 .mylogin.cnf
    mysqldump --defaults-extra-file=.mylogin.cnf --all-databases > backup.sql
    tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
fi
