#!/usr/bin/env bash
# pings argument received as string
#+ displays *Usage: 5-is_the_host_on_the_network {IP_ADDRESS}* if no args

if [ "$1" ]
then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
