#!/usr/bin/env bash
# sites-enabled/default shows it was configured to listen on 8080 and not 80, we replace thsi with sed
# remove existing /etc/nginx/sites-enabled/default file.
rm /etc/nginx/sites-enabled/default
# create a symbolic link
cp -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
