#!/usr/bin/env bash
# This script uses if to print Hi on the 9th line
#+ while printing "Best School" on the other 9 lines
i=0
while ((i < 10));
do
    if  [ $i -ne 8 ]; then
        echo "Best School"
    else
        echo "Best School"
        echo "Hi"
    fi
    ((i++))
done
