#!/bin/env bash
# This script uses if to print Hi on the 9th line
#+ while printing "Best School" on the other 9 lines
i=1
while [ "$i" -le "10" ];
do
    if  [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq "8" ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
