#!/usr/bin/env bash
# while loop condition using case

a=1
while [ "$a" -le "20" ];
do
    case $a in
    "4")
        echo "$a"
        echo "bad luck from China"
        ;;

    "9")
        echo "$a"
        echo "back luck from Japan"
        ;;

    "17")
        echo "$a"
        echo "bad luck from Italy"
        ;;

    *)
        echo "$a"
    ;;

    esac
    ((a++))
done